apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: skillpulse-backend
  namespace: monitoring
  labels:
    release: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  namespaceSelector:
    matchNames:
      - skillpulse
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
