CREATE DATABASE IF NOT EXISTS skillpulse;
USE skillpulse;

CREATE USER IF NOT EXISTS 'skillpulse'@'%' IDENTIFIED BY 'skillpulse123';
GRANT ALL PRIVILEGES ON skillpulse.* TO 'skillpulse'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS skills (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255),
  target_hours FLOAT DEFAULT 0,
  total_hours FLOAT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS learning_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  skill_id INT,
  hours FLOAT NOT NULL,
  log_date DATE NOT NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE
);
